// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS_System_DAL.Data;

#nullable disable

namespace POS_System_DAL.Migrations
{
    [DbContext(typeof(OnlinePosContext))]
    [Migration("20241028040312_updateGoodsId")]
    partial class updateGoodsId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS_System_DAL.Models.TblCustomer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("customer_id");

                    b.Property<int?>("Allowdebt")
                        .HasColumnType("int")
                        .HasColumnName("allowdebt");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("customer_address");

                    b.Property<int>("CustomerCounter")
                        .HasColumnType("int")
                        .HasColumnName("customer_counter");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("customer_phone");

                    b.HasKey("CustomerId")
                        .HasName("PK__tbl_cust__CD65CB854BC2BCF1");

                    b.ToTable("tbl_customer", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGood", b =>
                {
                    b.Property<string>("GoodsId")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("goods_id");

                    b.Property<string>("GoodsBrand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("goods_brand");

                    b.Property<int>("GoodsCounter")
                        .HasColumnType("int")
                        .HasColumnName("goods_counter");

                    b.Property<string>("GoodsName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("goods_name");

                    b.Property<int?>("GoodsStatus")
                        .HasColumnType("int")
                        .HasColumnName("goods_status");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("group_id");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("picture");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.HasKey("GoodsId")
                        .HasName("PK__tbl_good__40BA2239710FBC6A");

                    b.HasIndex("GroupId");

                    b.ToTable("tbl_goods", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGoodsgroup", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("group_id");

                    b.Property<int>("GroupCounter")
                        .HasColumnType("int")
                        .HasColumnName("group_counter");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("group_name");

                    b.Property<int?>("GroupStatus")
                        .HasColumnType("int")
                        .HasColumnName("group_status");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.HasKey("GroupId")
                        .HasName("PK__tbl_good__D57795A06351FF69");

                    b.ToTable("tbl_goodsgroup", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGoodsproperty", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("property_id");

                    b.Property<string>("GoodsId")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("property_name");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.HasKey("PropertyId");

                    b.HasIndex("GoodsId");

                    b.ToTable("tbl_goodsproperty", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGoodssupplied", b =>
                {
                    b.Property<int>("GoodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("goods_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsId"));

                    b.Property<string>("GoodsName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("goods_name");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.Property<string>("SupplierId")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("supplier_id");

                    b.HasKey("GoodsId");

                    b.HasIndex("SupplierId");

                    b.ToTable("tbl_goodssupplied", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGoodsunit", b =>
                {
                    b.Property<string>("GoodsUnit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("goods_unit");

                    b.Property<string>("Barcode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("barcode");

                    b.Property<string>("GoodsId")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("goods_id");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.Property<int?>("UnitSize")
                        .HasColumnType("int")
                        .HasColumnName("unit_size");

                    b.Property<int?>("UnitStatus")
                        .HasColumnType("int")
                        .HasColumnName("unit_status");

                    b.Property<int?>("UnitStock")
                        .HasColumnType("int")
                        .HasColumnName("unit_stock");

                    b.HasKey("GoodsUnit");

                    b.HasIndex("GoodsId");

                    b.ToTable("tbl_goodsunit", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("EnglishText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("english_text");

                    b.Property<string>("InvestText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invest_text");

                    b.Property<string>("LinkedView")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("linked_view");

                    b.Property<string>("LocalText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("local_text");

                    b.Property<int?>("MenuOrder")
                        .HasColumnType("int")
                        .HasColumnName("menu_order");

                    b.HasKey("MenuId");

                    b.ToTable("tbl_menu", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblMessageText", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("message_id");

                    b.Property<string>("EnglishMessage")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("english_message");

                    b.Property<string>("InvestMessage")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("invest_message");

                    b.Property<string>("LocalMessage")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("local_message");

                    b.HasKey("MessageId")
                        .HasName("PK_message_text");

                    b.ToTable("tbl_message_text", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblPo", b =>
                {
                    b.Property<string>("PosNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("pos_number");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime")
                        .HasColumnName("cancel_date");

                    b.Property<string>("CancelPerson")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cancel_person");

                    b.Property<string>("CashierId")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("cashier_id");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("Payer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payer");

                    b.Property<DateTime?>("Paymentdate")
                        .HasColumnType("datetime")
                        .HasColumnName("paymentdate");

                    b.Property<int?>("PosCounter")
                        .HasColumnType("int")
                        .HasColumnName("pos_counter");

                    b.Property<string>("PosCreator")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pos_creator");

                    b.Property<double?>("PosCustomerpay")
                        .HasColumnType("float")
                        .HasColumnName("pos_customerpay");

                    b.Property<DateTime?>("PosDate")
                        .HasColumnType("datetime")
                        .HasColumnName("pos_date");

                    b.Property<double?>("PosDiscount")
                        .HasColumnType("float")
                        .HasColumnName("pos_discount");

                    b.Property<double?>("PosExchange")
                        .HasColumnType("float")
                        .HasColumnName("pos_exchange");

                    b.Property<int?>("PosPaymentmethod")
                        .HasColumnType("int")
                        .HasColumnName("pos_paymentmethod");

                    b.Property<int?>("PosPaymenttype")
                        .HasColumnType("int")
                        .HasColumnName("pos_paymenttype");

                    b.Property<int?>("PosStatus")
                        .HasColumnType("int")
                        .HasColumnName("pos_status");

                    b.Property<double?>("PosTopay")
                        .HasColumnType("float")
                        .HasColumnName("pos_topay");

                    b.Property<double?>("PosTotal")
                        .HasColumnType("float")
                        .HasColumnName("pos_total");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.HasKey("PosNumber")
                        .HasName("PK__tbl_pos__60F6E28FA0CDCCE5");

                    b.ToTable("tbl_pos", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblPosdetail", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("barcode");

                    b.Property<string>("GoodsId")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("goods_id");

                    b.Property<string>("GoodsName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("goods_name");

                    b.Property<int?>("ItemOrder")
                        .HasColumnType("int")
                        .HasColumnName("item_order");

                    b.Property<double?>("ItemPrice")
                        .HasColumnType("float")
                        .HasColumnName("item_price");

                    b.Property<double?>("ItemQuantity")
                        .HasColumnType("float")
                        .HasColumnName("item_quantity");

                    b.Property<string>("ItemUnit")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("item_unit");

                    b.Property<double?>("LineDiscount")
                        .HasColumnType("float")
                        .HasColumnName("line_discount");

                    b.Property<double?>("LineTotal")
                        .HasColumnType("float")
                        .HasColumnName("line_total");

                    b.Property<string>("PosNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("pos_number");

                    b.Property<string>("Property")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("property");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("property_value");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("float")
                        .HasColumnName("sub_total");

                    b.HasIndex("PosNumber");

                    b.ToTable("tbl_posdetail", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblPropertygroup", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("property_id");

                    b.Property<int>("PropertyCounter")
                        .HasColumnType("int")
                        .HasColumnName("property_counter");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("property_name");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.HasKey("PropertyId")
                        .HasName("PK__tbl_prop__735BA463E3BE5D3A");

                    b.ToTable("tbl_propertygroup", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblReceipt", b =>
                {
                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("receipt_number");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime")
                        .HasColumnName("cancel_date");

                    b.Property<string>("CancelPerson")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cancel_person");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentPerson")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_person");

                    b.Property<int?>("PaymentType")
                        .HasColumnType("int")
                        .HasColumnName("payment_type");

                    b.Property<int?>("PaymenyStatus")
                        .HasColumnType("int")
                        .HasColumnName("paymeny_status");

                    b.Property<int>("ReceiptCounter")
                        .HasColumnType("int")
                        .HasColumnName("receipt_counter");

                    b.Property<string>("ReceiptCreator")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("receipt_creator");

                    b.Property<DateTime?>("ReceiptDate")
                        .HasColumnType("datetime")
                        .HasColumnName("receipt_date");

                    b.Property<double?>("ReceiptDiscount")
                        .HasColumnType("float")
                        .HasColumnName("receipt_discount");

                    b.Property<int?>("ReceiptStatus")
                        .HasColumnType("int")
                        .HasColumnName("receipt_status");

                    b.Property<double?>("ReceiptTopay")
                        .HasColumnType("float")
                        .HasColumnName("receipt_topay");

                    b.Property<double?>("ReceiptTotal")
                        .HasColumnType("float")
                        .HasColumnName("receipt_total");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("received_date");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.Property<string>("SupplierId")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("supplier_name");

                    b.Property<double?>("SupplierTopay")
                        .HasColumnType("float")
                        .HasColumnName("supplier_topay");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.Property<string>("UpdatePerson")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("update_person");

                    b.HasKey("ReceiptNumber")
                        .HasName("PK__tbl_rece__89FE4B74FBD48252");

                    b.ToTable("tbl_receipt", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblReceiptdetail", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("barcode");

                    b.Property<string>("GoodsId")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("goods_id");

                    b.Property<string>("GoodsName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("goods_name");

                    b.Property<int?>("ItemOrder")
                        .HasColumnType("int")
                        .HasColumnName("item_order");

                    b.Property<double?>("ItemPrice")
                        .HasColumnType("float")
                        .HasColumnName("item_price");

                    b.Property<double?>("ItemQuantity")
                        .HasColumnType("float")
                        .HasColumnName("item_quantity");

                    b.Property<string>("ItemUnit")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("item_unit");

                    b.Property<double?>("LineDiscount")
                        .HasColumnType("float")
                        .HasColumnName("line_discount");

                    b.Property<double?>("LineTotal")
                        .HasColumnType("float")
                        .HasColumnName("line_total");

                    b.Property<string>("Property")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("property");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("property_value");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("receipt_number");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("float")
                        .HasColumnName("sub_total");

                    b.HasIndex("ReceiptNumber");

                    b.ToTable("tbl_receiptdetail", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblScreenText", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("company_id");

                    b.Property<string>("StoreId")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("store_id");

                    b.Property<string>("ScreenName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("screen_name");

                    b.Property<string>("ItemName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("item_name");

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("english_text");

                    b.Property<string>("InvestText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("invest_text");

                    b.Property<string>("LocalText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("local_text");

                    b.HasKey("CompanyId", "StoreId", "ScreenName", "ItemName")
                        .HasName("PK_screen_text");

                    b.ToTable("tbl_screen_text", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblSellprice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("barcode");

                    b.Property<string>("GoodsId")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("goods_id");

                    b.Property<string>("GoodsUnit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("goods_unit");

                    b.Property<int?>("SellNumber")
                        .HasColumnType("int")
                        .HasColumnName("sell_number");

                    b.Property<int?>("SellPrice")
                        .HasColumnType("int")
                        .HasColumnName("sell_price");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.HasKey("Id")
                        .HasName("PK__tbl_sell__3213E83FB1CF1D26");

                    b.HasIndex("GoodsId");

                    b.ToTable("tbl_sellprice", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblStatusText", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("english_name");

                    b.Property<string>("InvestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invest_name");

                    b.Property<string>("LocalName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("local_name");

                    b.HasKey("StatusId")
                        .HasName("PK_status_text");

                    b.ToTable("tbl_status_text", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblStore", b =>
                {
                    b.Property<string>("StoreId")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("store_id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("company_id");

                    b.Property<string>("InvLanguage")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("inv_language");

                    b.Property<string>("LocalLanguage")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("local_language");

                    b.Property<string>("StoreAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("store_address");

                    b.Property<string>("StoreLogo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("store_logo");

                    b.Property<string>("StoreName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("store_name");

                    b.Property<string>("StorePhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("store_phone");

                    b.Property<int?>("StoreStatus")
                        .HasColumnType("int")
                        .HasColumnName("store_status");

                    b.HasKey("StoreId");

                    b.ToTable("tbl_store", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblSupplier", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("supplier_id");

                    b.Property<int?>("AllowDebt")
                        .HasColumnType("int")
                        .HasColumnName("allow_debt");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.Property<string>("SupplierAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("supplier_address");

                    b.Property<int>("SupplierCounter")
                        .HasColumnType("int")
                        .HasColumnName("supplier_counter");

                    b.Property<string>("SupplierEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("supplier_email");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("SupplierPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("supplier_phone");

                    b.Property<int?>("SupplierType")
                        .HasColumnType("int")
                        .HasColumnName("supplier_type");

                    b.HasKey("SupplierId")
                        .HasName("PK__tbl_supp__6EE594E835736B89");

                    b.ToTable("tbl_supplier", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblUser", b =>
                {
                    b.Property<string>("LoginName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login_name");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentifyString")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("identify_string");

                    b.Property<string>("PassWord")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("pass_word");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("store_id");

                    b.Property<string>("UserLanguage")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("user_language");

                    b.Property<int?>("UserLevel")
                        .HasColumnType("int")
                        .HasColumnName("user_level");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int")
                        .HasColumnName("user_status");

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.HasKey("LoginName");

                    b.ToTable("tbl_user", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblUserright", b =>
                {
                    b.Property<int?>("Assigned")
                        .HasColumnType("int")
                        .HasColumnName("assigned");

                    b.Property<string>("LoginName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login_name");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<int>("RightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("right_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RightId"));

                    b.Property<string>("StoreId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("store_id");

                    b.HasIndex("LoginName");

                    b.HasIndex("MenuId");

                    b.ToTable("tbl_userright", (string)null);
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGood", b =>
                {
                    b.HasOne("POS_System_DAL.Models.TblGoodsgroup", "Group")
                        .WithMany("TblGoods")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__tbl_goods__group__693CA210");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGoodsproperty", b =>
                {
                    b.HasOne("POS_System_DAL.Models.TblGood", "Goods")
                        .WithMany()
                        .HasForeignKey("GoodsId")
                        .HasConstraintName("FK_tbl_goodsproperty_tbl_goods");

                    b.HasOne("POS_System_DAL.Models.TblPropertygroup", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__tbl_goods__prope__6A30C649");

                    b.Navigation("Goods");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGoodssupplied", b =>
                {
                    b.HasOne("POS_System_DAL.Models.TblSupplier", "Supplier")
                        .WithMany("TblGoodssupplieds")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__tbl_goods__suppl__6C190EBB");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGoodsunit", b =>
                {
                    b.HasOne("POS_System_DAL.Models.TblGood", "Goods")
                        .WithMany()
                        .HasForeignKey("GoodsId")
                        .HasConstraintName("FK__tbl_goods__goods__6D0D32F4");

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblPosdetail", b =>
                {
                    b.HasOne("POS_System_DAL.Models.TblPo", "PosNumberNavigation")
                        .WithMany()
                        .HasForeignKey("PosNumber")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_posde__pos_n__6E01572D");

                    b.Navigation("PosNumberNavigation");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblReceiptdetail", b =>
                {
                    b.HasOne("POS_System_DAL.Models.TblReceipt", "ReceiptNumberNavigation")
                        .WithMany()
                        .HasForeignKey("ReceiptNumber")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_recei__recei__6EF57B66");

                    b.Navigation("ReceiptNumberNavigation");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblSellprice", b =>
                {
                    b.HasOne("POS_System_DAL.Models.TblGood", "Goods")
                        .WithMany("TblSellprices")
                        .HasForeignKey("GoodsId")
                        .HasConstraintName("FK__tbl_sellp__goods__6FE99F9F");

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblUserright", b =>
                {
                    b.HasOne("POS_System_DAL.Models.TblUser", "LoginNameNavigation")
                        .WithMany()
                        .HasForeignKey("LoginName")
                        .HasConstraintName("FK__tbl_userr__login__71D1E811");

                    b.HasOne("POS_System_DAL.Models.TblMenu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .HasConstraintName("FK__tbl_userr__menu___70DDC3D8");

                    b.Navigation("LoginNameNavigation");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGood", b =>
                {
                    b.Navigation("TblSellprices");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblGoodsgroup", b =>
                {
                    b.Navigation("TblGoods");
                });

            modelBuilder.Entity("POS_System_DAL.Models.TblSupplier", b =>
                {
                    b.Navigation("TblGoodssupplieds");
                });
#pragma warning restore 612, 618
        }
    }
}
